pygrametl/tables.py

As a response to #12, sorry to be so late. 
- A new `__init__` argument `orderingatt` is added, which is used later to construct sql queries to find the newest version; `versionatt` become optional, with `None` as default
- `versionatt` in `self.keylookupsql`, `self.keyversionlookupsql` as well as `sql` inside `self.__prefillcaches` are all replaced with `orderingatt`
- Codes that modifies `versionatt` are now wrapped under an if statement, so they won't be executed unless `versionatt` is not `None`, essentially the same as what we do with `fromatt` and `toatt`
- Is the name `orderingatt` clear enough to indicate what it does? Any better name?
- In most cases I can imagine, the most likely candidates of `orderingatt` are `toatt`, `fromatt`, and `versionatt`. So this code somehow …

make versionatt in SlowlyChangingDimension optional

---

pygrametl/FIFODict.py
pygrametl/JDBCConnectionWrapper.py
pygrametl/__init__.py
pygrametl/datasources.py
pygrametl/parallel.py
pygrametl/steps.py
pygrametl/tables.py

In last commit, when calling `scdensure`, local variable `versionatt` is not defined if `self.versionatt` is None, resulting in an "referenced before assignment" error in the following code. This patch adds a fallback case to prevent that.
```Python
if self.versionatt:
versionatt = (namemapping.get(self.versionatt) or self.versionatt)
else:
versionatt = None
```
Also, I try to prettify arguments list in the docstrings. In my local environment, I use Spyder as an IDE. I find that arugments list in the doc messed up. Some items join to the preceding paragraph instead of being a separate item.
I checked [the document of reStructuredText](http://docutils.sourceforge.net/docs/user/rst/quickref.html#bullet-lists) and learned that
>Note that a blank line is required before the first item and …

fix bug in scdensure when versionatt is None

---

CHANGELOG.rst
docs/examples/datasources.rst
pygrametl/datasources.py

MappingSource allows a callable to be executed for all elements of a column,
for example type casting can be performed by simple passing in {'Price':Int}.

Added the MappingSource datasource

---

CHANGELOG.rst
docs/examples/datasources.rst
pygrametl/datasources.py

The PandasSource can be used to convert a Pandas DataFrame to an iterator of
dict, and as a result, possible to load into a data warehouse using pygrametl.

Added PandasSource, a datasource for DataFrames

---

docs/examples/dimensions.rst

Resolves #2 by updating the first example for SnowflakedDimension so that the
example acutally creates a normalized hierachy instead of a denomarlized
hierachy as was intended.

Fixed the first example for Snowflakedimension

---

CHANGELOG.rst
pygrametl/tables.py

In a small benchmark, loading 50 million auto-generated rows into PostgreSQL on a laptop using psycopg2, ``BatchFactTable.__insertvalues`` (17 Minutes) was approximately four time faster than ``BatchFactTable.__insertexecutemany`` (70 Minutes).

Fix #19 by adding batch loading using INSERT INTO

---

CHANGELOG.rst
pygrametl/__init__.py

Error 1: The function did not check whether 'fromdate' and 'todate' are strings before calling .split
Error 2: The function used dict.iteritems() which is not supported in Python 3.

Corrected 2 errors in datespan function 

---

.gitignore
CHANGELOG.rst
pygrametl/tables.py

This should fix issue #48 
The following should be able to run after applying this fix.
```python
import sqlite3
from pygrametl import ConnectionWrapper, parallel
from pygrametl.tables import BulkFactTable, DecoupledFactTable, FactTablePartitioner
connection = sqlite3.connect(":memory:")
cursor = connection.execute("CREATE TABLE test_table(ra INT, rb INT, ma INT, mb INT)")
connection.commit()
cursor.close()
def bulkloader(name: str, attributes, fieldsep, rowsep, nullval, filehandle):
pass
cw = ConnectionWrapper(connection)
scw = parallel.shareconnectionwrapper(cw, userfuncs=[bulkloader])
fact = DecoupledFactTable(
BulkFactTable(
name="test_table",
keyrefs=["ra", "rb"],
measures=["ma", "mb"],
bulkloader=scw.copy().bulkloader,
usefilename=True
),
returnvalues=False,
)
partitioner = …
```

Added missing BulkFactTable attributes

---

CHANGELOG.rst
pygrametl/__init__.py
pygrametl/tables.py

As described in GitHub issue #50 the current implementation of `BatchFactTable` cannot insert rows containing `NULL` values if `usemultirow=True` (the default is `False`). This PR adds the function `getsqlfriendlystr()` which converts values to strings that can be used in an SQL expression. It currently converts `None` to `"NULL"`, encapsulates strings in single quotes, escapes all single quotes in strings by doubling them, and converts the remaining values to strings using `str()`. The PR also replaces `BatchFactTable`'s internal value to string conversation logic with a call to  `getsqlfriendlystr()`.

Fix BatchFactTable not converting all None to NULL

---

CHANGELOG.rst
pygrametl/tables.py

This PR adds an explicit `raise ValueError` if a `rowexpander` does not return a `dict` with the name of the `rowexpander` that failed to simplify debugging.

Raise an error if a rowexpander does not return

---

CHANGELOG.rst
pygrametl/__init__.py

ymdparser and ymdhmsparser now accept datetime.date(time) as input. Any other input is cast to a str and quotes are removed before it is split into the needed parts to create a datetime.date(time).
Closes GitHub issue #40 and closes GitHub PR #41 (which inspired this).

More robust ymdparser and ymdhmsparser.

---

docs/examples/bulkloading.rst
docs/examples/parallel.rst

This PR closes #46 and #47 by [documenting which platforms can execute parallel ETL flows](https://github.com/chrthomsen/pygrametl/blob/document-parallel-limitation/docs/examples/parallel.rst) implemented pygrametl. Currently, pygrametl supports executing parallel ETL flows using CPython on platforms that start new processes using [`fork`](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) and [Jython](https://github.com/jython/jython). Thus, executing a parallel ETL flow natively on Microsoft Windows using CPython is not supported, and macOS must be configured to use `fork` using [`multiprocessing.set_start_method('fork')`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method) due to the issues with macOS's `fork` …

Specify which platforms can run parallel ETL flows

---

CHANGELOG.rst
docs/examples/datasources.rst
pygrametl/datasources.py
tests/test_datasources.py
tests/utilities.py

This PR adds a new class to `datasources.py` named `SQLTransformingSource` which provides support for transforming rows using SQL by loading them into a temporary table in an RDBMS and then retrieving them using an SQL query. There are two open questions related to the current implementation: 
1. Can/should a most robust method for checking if `targetconnection` is one the `ConnectionWrapper` types be used? Currently the code simply assumes `targetconnection` is one of the `ConnectionWrapper` types if it implements a method named `getunderlyingmodule`.
2. Can/should `quote`, `quotelist`, and `insertsql` be shared be between `Dimension` and `SQLTransformingSource` and if so how?

Add SQLTransformingSource

---

CHANGELOG.rst
pygrametl/tables.py
tests/tables/test_Dimension.py

This PR adds support for updating either all or only the latest version of a member when type 1 updates are being performed to `SlowlyChangingDimension` to fix issue #64. The updated versions are still being deleted from the cache which probably is not necessary, but since deleting them from the cache should always be safe I have opted for not optimizing the caching until after the code that performs the type 1 updates is done, tested, and reviewed.

SlowlyChangingDimension type1 update only latest

---

.github/workflows/python-unittest-on-pr-and-push.yml

This PR renames `master` to `main` in GitHub Actions.

Rename master to main in GitHub Actions

---

README.rst

This PR adds a badge from [shields.io](https://shields.io/badges/py-pi-downloads) which shows the number of times pygrametl have been downloaded from PyPI according to [pypistats](https://pypistats.org/) which uses [data](https://pypistats.org/about) that the Python Software Foundation makes publicly available on [Google BigQuery](https://bigquery.cloud.google.com/table/bigquery-public-data:pypi.downloads).

Add PyPI downloads badge from shields.io

---

CHANGELOG.rst
docs/examples/bulkloading.rst

This PR resolves the issue #74

psycopg2 bulkloader docs update

---

CHANGELOG.rst
pygrametl/datasources.py

Added fetch_size constructor param

---

README.rst

This PR fixes #78 by replacing all links to pygrametl.com with pygrametl.org.

Replace pygrametl.com with pygrametl.org

---

CHANGELOG.rst
pygrametl/datasources.py
tests/test_datasources.py

Previously, `MappingSource` only behaved as expected when only passing a single callable, as it would yield a new row for each callable.
Now, we instead only yield a row for each row in the original datasource.
I have also added a few tests to verify this behavior

Fix `MappingSource` duplicating rows when passing multiple callables
